# Generated by Django 2.2.12 on 2022-01-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=50, verbose_name='菜单类别名')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_name', models.CharField(max_length=50, verbose_name='菜名')),
                ('comment', models.FloatField(verbose_name='好评度')),
                ('img_link', models.ImageField(upload_to='', verbose_name='图片')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('price', models.FloatField(verbose_name='单价')),
                ('volume', models.IntegerField(verbose_name='月销量')),
                ('Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Style')),
            ],
        ),
    ]
